CREATE DATABASE garage;
GO
 
USE garage;

CREATE TABLE Brands
(
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(20) UNIQUE NOT NULL
);
GO

CREATE TABLE Models
(
Id INT PRIMARY KEY IDENTITY,
BrandId INT REFERENCES Brands(Id),
[Name] NVARCHAR(20) UNIQUE NOT NULL
);
GO

CREATE TABLE Cars
(
Id INT PRIMARY KEY IDENTITY,
ModelId INT REFERENCES Models(Id),
VIN NVARCHAR(20) UNIQUE NOT NULL,
TypeOfEngine NVARCHAR(20) NOT NULL,
EngineCapacity DECIMAL(19,4) NOT NULL,
Transmission NVARCHAR(20) NOT NULL,
Color NVARCHAR(20) NOT NULL,
Price MONEY,
IsAvailable BIT
);

CREATE TABLE Clients
(
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(20) NOT NULL,
[Login] NVARCHAR(20) UNIQUE NOT NULL,
[Password] NVARCHAR(20) NOT NULL,
MoneyAccount MONEY DEFAULT 0
);